site_name: DentalLab Manager
site_author: 전국치과기공소경영자회
google_analytics: ['UA-143286387-1', 'dentallabmanager.github.io'] 
copyright: ©2019 전국치과기공소경영자회 (https://repre.kdtech.or.kr)
# theme: readthedocs
nav: 
  - 소개: index.md
  - 다운로드: download.md
  - 원격지원: remote.md
  - 설치메뉴얼: install.md
  - 메뉴도움말 : menu.md
  - 간략설명서 : brief.md
  - (경영자회)게시판 : https://repre.kdtech.or.kr/board/board.asp?table=BD_rental_manager&wpage=8&tpage=1
  